
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clone_kadai_development




test:
  <<: *default
  database: clone_kadai_test

production:
  <<: *default
  database: clone_kadai_production
  username: clone_kadai
  password: <%= ENV['CLONE_KADAI_DATABASE_PASSWORD'] %>
